### ISSUE TITLE
missing style.css

### ISSUE THREAD

**Issue by knlklabacka** [nathansebhastian/finly#1]
Hello!   I'm trying to follow along with your book.  I'm stuck on chapter 5.  I can't get the daisyui working.  I don't want to assume that in chapter 5 /views/partials/head.ejs file might have an error.  The <link href="/styles/style.css">, this file does not exist.  Should it be tailwindcss.css? 

Thank you!

**Comment by NathanSebhastian** [comment]
Hello, have you run the `devcss` command from the terminal to generate the `style.css` file?

As for the DaisyUI, you need to add it in Tailwind config file as shown in the book:

```js
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./views/**/*.ejs'],
  theme: {
    extend: {},
  },
  plugins: [require('daisyui')], // add DaisyUI here
};
```

**Comment by knlklabacka** [comment]
Thank you sir!  Running the devcss command fixed the issue!  I appreciate the help.
